### ISSUE TITLE
Parse dashboard wrapper

### ISSUE THREAD

**Issue by thiago-rls** [bajpangosh/Install-Parse-Server-on-Ubuntu#1]
Hey! 

I tried your script, but at the end something goes wrong. 

The parse-dashboard-wrapper is showing "errored" in the table.

Have you faced this issue?

**Comment by bajpangosh** [comment]
No, I will check it out. please wait for the update.

Thank you.

**Comment by thiago-rls** [comment]
Okay, I posted in the wrong version! I am using the 18.04LTS version. Sorry for that!

Thank you!

**Comment by thiago-rls** [comment]
I'm closing!

I was trying to install it as a sudo user. It worked logging as root.

**Comment by bajpangosh** [comment]
Okey, thanks dude.
