### ISSUE TITLE
Running into Cors Issues

### ISSUE THREAD

**Issue by MackyBwoy22** [bajpangosh/Install-Parse-Server-on-Ubuntu#7]
Need help resolving cors issues im getting from the dashboard. Access to XMLHttpRequest at 'https://app.gated.com/parse/schemas' from origin 'https://dash.gated.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by bajpangosh** [comment]
please use this script **https://github.com/bajpangosh/Install-Parse-Server-on-Ubuntu/tree/master/ubuntu-18.04**
